MvcCourse/Models/DocumentationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Web.PublishedContentModels;       //generated models
//namespace Umbraco.Web.PublishedContentModels

namespace MvcCourse.Models
{
    public class DocumentationViewModel : Documentation     //PublishedContentModel
    {
        //this assure alle the inherited properties to be added to the Vmodel
        public DocumentationViewModel(IPublishedContent content) : base(content)
        {
        }
        //add here extra custom property to avoid service logic on the html page
        public IEnumerable<LandingPage> LandingPages { get; internal set; }
        //where this LandingPage is defined? this is aanother Umbraco generated model that  will be included in the viewModel

        //add Images to display in the view to via this view model
        //this value will be gathered from the IPublished content available from the Documentations generated model and casted to this type
        public IEnumerable<Image> AllImages { get; internal set; }
    }
}

MvcCourse/Controllers/BrokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCourse.Models;
using Umbraco.Web.Mvc;

namespace MvcCourse.Controllers
{
    public class BrokenController : SurfaceController
    {
        // GET: Broken
        public ActionResult Submit(BrokenFormModel model)
        {
            //In cases the model does not validate
            if (ModelState.IsValid == false)
                return CurrentUmbracoPage();

            //this will explode when = 0
            var result = 1000/model.ANumber;

            
            return RedirectToCurrentUmbracoPage();
        }
    }
}

MvcCourse/Controllers/DocumentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientDependency.Core;
using ImageProcessor.Web.Helpers;
using Umbraco.Web.Models;       //RenderModel
using Umbraco.Web.Mvc;
using MvcCourse.Models;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.PublishedContentModels;

//for the viewModel custom model with custom property

namespace MvcCourse.Controllers
{
    public class DocumentationController : RenderMvcController
    {
        // GET: Documentation
        public override ActionResult Index(RenderModel model)
        {
            //add here the logic that was in the view to get all the product that are referenced in the Documentation content
            //PRODUCTs page URL to be displayed - use the relation service to get the relations
            //get the 'related' landing pages
            var ids = UmbracoContext
                .Application.Services
                .RelationService.GetByParentId(model.Content.Id)
                .Select(x => x.ChildId);

            ////fetch them as nodes
            //var products = Umbraco.TypedContent(ids)
            //    .Where(x => x.DocumentTypeAlias == "landingPage").ToList();
            var products = Umbraco.TypedContent(ids).OfType<LandingPage>();

            //IMAGES
            //var images = model.Content.Images.OfType<Folder>()
            //    .SelectMany(x => x.Children().OfType<Image>());
            //property in Documentation Model
            //IEnumerable<IPublishedContent> Images

            var images = model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("Images")       //doc Typr property in Documentation
            .OfType<Folder>().SelectMany(x => x.Children().OfType<Image>());                            //type to the VM property Ienum<Image>
     
            var list = CurrentPage.GetPropertyValue("Images");

            //create the custom viewmodel adding the product to the custom property LnadingPages fo rthe products referenced in the content
            var viewmodel = new DocumentationViewModel(model.Content)       // set the inherited content
            {
                //set the custom property LandingPages
                LandingPages = products,
                //get the property from the published content inherited and type to the custom property for images
                AllImages = images
            };

            //returns the new model to the view
            return CurrentTemplate(viewmodel);


            //return base.Index(model);
        }
    }
}

MvcCourse/Controllers/DocumentationFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCourse.Helper;
using MvcCourse.Models;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;

namespace MvcCourse.Controllers
{
    public class DocumentationFormController : SurfaceController                //RenderMvcController
    {
        //1 rendering the form 
        //2 receiving update to post - update

        // GET: DocumentationForm - load the form filled with the content from the doc type
        //his fires once the used click on edit
        [ChildActionOnly]
        public ActionResult Render(Documentation model) //pass in the @Model.Content the content of the doc type 'Documentation'
        {
            //we receive here the model from the Documentation page
            DocumentationFormModel documentationFormModel = new DocumentationFormModel()
            {
                BodyText = model.BodyText.ToString(),
                Name = model.Name
            };
            //we pass the model to the partial view that contains the form
            //the partial view for the form accepts this model '@model MvcCourse.Models.DocumentationFormModel'
            return PartialView("~/Views/Partials/DocumentationForm.cshtml", documentationFormModel);
        }

        //here are posted the new content of the documentatation doc type
        [HttpPost]
        public ActionResult Submit(DocumentationFormModel model)
        {
            if (ModelState.IsValid == false)
                return CurrentUmbracoPage();

            var currentPageId = CurrentPage.Id;                                 //IPublishedContent
            var content = Services.ContentService.GetById(currentPageId);       //ServiceContext
            content.Name = model.Name;
            var bodyTextProperty = Documentation.GetModelPropertyType(p => p.BodyText);
            content.SetValue(bodyTextProperty.PropertyTypeAlias, model.BodyText);       // this is Dynamic

            //ex. 5 
            var mediaService = Services.MediaService;
            if (model.Images.HasFiles() && model.Images.ContainsImages())
            {
                var imagesProperty = Documentation.GetModelPropertyType(x => x.Images);
                //in BOffice Content section I can set a folder to the documentation content to store the uploaded images
                //or not. If not there isn't a folder available and the result of the following line is folderId = 0
                var folderId = content.GetValue<int>(imagesProperty.PropertyTypeAlias);

                if (folderId <= 0)
                {
                    //if no folder has been set in the BO documentation scontent in the field Images
                    //then create one using default settings
                    //here I create the folder: 
                    //("the name given to the folder", parentId, mediatypeAlias)
                    var folder = mediaService.CreateMedia(model.Name, -1, Folder.ModelTypeAlias);       //create folder

                    //save the folder to the MEDIA section too
                    mediaService.Save(folder);

                    folderId = folder.Id;
                    content.SetValue(imagesProperty.PropertyTypeAlias, folderId);
                }

                //if user uploaded a picture in the Edit form, then add to the folder that will be added to the media section folder too
                foreach (var file in model.Images)
                {
                    if (file.IsImage())
                    {
                        //process files images

                        //create Media of type Image
                        var mediaImage = mediaService.CreateMedia(file.FileName, folderId, Image.ModelTypeAlias);
                        var umbracoFileProperty = Image.GetModelPropertyType(i => i.UmbracoFile);
                        mediaImage.SetValue(umbracoFileProperty.PropertyTypeAlias, file);           //dynamic porperty for the images
                        //save image to set folder
                        mediaService.Save(mediaImage);
                    }
                }
            }

            Services.ContentService.SaveAndPublishWithStatus(content);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

MvcCourse/Views/Broken.cshtml
@using MvcCourse.Models
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="page-header">
                <h1>@Umbraco.Field("pageName")</h1>
            </div>
            
            @Umbraco.Field("bodyText")


            @Html.Partial("/Views/Partials/brokenform.cshtml", new BrokenFormModel())

        </div>
    </div>
</div>    
    
    

MvcCourse/Views/Documentation.cshtml
@*@inherits UmbracoTemplatePage<Documentation>*@

@*@ex. 7 refactoring using custom viewModel and Controller*@
@inherits UmbracoTemplatePage<MvcCourse.Models.DocumentationViewModel>
@{
    Layout = "Master.cshtml";

    ////ex. 7 this will be calculated in the controller Documentation Index meth.

    //////get images in the Media folder assigned for the uploaded images
    //var images = Model.Content.Images.OfType<Folder>()
    //                .SelectMany(x => x.Children().OfType<Image>());

    //the below code is made redundant with model + custom controller
    //Model.Content.LandingPages is populated with the related nodes fetched from content cache
    ////get the related landing pages
    //var ids = UmbracoContext
    //                .Application.Services
    //                .RelationService.GetByParentId(Model.Content.Id)
    //                .Select(x => x.ChildId);

    ////fetch them as nodes
    //var products = Umbraco.TypedContent(ids)
    //                       .Where(x => x.DocumentTypeAlias == "landingPage").ToList();
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
          <div class="page-header">
            @*<a class="btn btn-default pull-right" href="@Model.Content.Url/edit">Edit</a>*@
            @*EDIT BUTTON to load the partial view to update the documentations*@
            <a class="btn btn-default pull-right" href="@Model.Content.Url?altTemplate=Edit">Edit Documentation content</a>
            <h1>@Umbraco.Field("pageName")</h1>
          </div>

          @Umbraco.Field("bodyText")
          
          @*render the relation to a product if the product name is contained in the content of the page*@
          @*@if (products.Any())
          {
              <hr />
              <h4>Documentation Applies to Products - relations:</h4>
              <ul>
                  @foreach (var landingPage in products)
                  {
                      <li><a href="@landingPage.Url">@landingPage.Name</a></li>
                  }
              </ul>
          }*@

          @*ex. 7 refactoring using viewmodel instead with the property 'LandingPages'*@
          @if (Model.Content.LandingPages.Any())
          {
              <hr />
              <h4>Documentation Applies to Products - relations:</h4>
              <ul>
                  @foreach (var landingPage in Model.Content.LandingPages)
                  {
                      <li><a href="@landingPage.Url">@landingPage.Name</a></li>
                  }
              </ul>
          }
          else
          {
            <h4 style="color:coral">The documentation doesn't contain relation to any product :/</h4>
          }

          @*render images if contained in the folder*@
          @*@if (images.Any())
          {
              <h4>Documentation media - images:</h4>
              foreach (var image in images)
              {
                  <img src="@Url.GetCropUrl(image, "thumb")" alt="..." class="img-thumbnail">
              }
          }*@

          @* ex 7 - *@
          @if (Model.Content.AllImages.Any())
          {
              <h4>Documentation media - images:</h4>
              foreach (var image in Model.Content.AllImages)
              {
                  <img src="@Url.GetCropUrl(image, "thumb")" alt="..." class="img-thumbnail">
              }
          }
          else
          {
            <h4 style="color:red">The documentation doesn't contain images :/</h4>
          }
        </div>
        <div class="col-md-3">

            <ul class="nav nav-list">
                @foreach (var item in CurrentPage.Children)
                {
                    <li>
                        <a href="@item.Url">@item.Name</a>
                    </li>
                }
            </ul>

            <dl class="nav nav-list" id="doc-history-list"></dl>

            <button id="doc-history" class="btn btn-default"
                    data-doc-id="@CurrentPage.Id">
                Load revision history
            </button>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <footer>
                Updated by @Umbraco.Field("writerName") on @Umbraco.Field("updateDate", formatAsDate: true)
            </footer>
        </div>
    </div>
</div>

MvcCourse/Views/Edit.cshtml
@*@inherits Umbraco.Web.Mvc.UmbracoTemplatePage*@

@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<Documentation>

@{
	Layout = "Master.cshtml";
}

@* We land here when the user clcks the button 'EDIT...' *@
@* this page will be displayed and the an Action is called to the server: the action Render will render a partial view fro the form *@

<div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="page-header">
          <h1> Edit (page content) me: @Umbraco.Field("pageName") </h1>
          @*<h1> Edit me: @Model.Content.Name page content</h1>*@
        </div>
        @* call to the server to render a partial view indeicated in the controller*@
        @Html.Action("Render", "DocumentationForm", new { model = Model.Content })
      </div>
    </div>
</div>

MvcCourse/Views/Homepage.cshtml
@*@inherits UmbracoTemplatePage*@

@inherits UmbracoTemplatePage<Homepage>
@{
	Layout = "Master.cshtml";

  var profiler = UmbracoContext.Application.ProfilingLogger;
  using (profiler.DebugDuration<UmbracoTemplatePage>("Measuring Parsing algorithm. My profiler message:"))
  {
    System.Threading.Thread.Sleep(1000);
  }
}

<!-- promo slider html -->
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
		<div class="item active" style="background-image:url('/images/HQ_9975.jpg');">
			<div class="carousel-caption">
				<h2>Slide 1</h2>
				<h3>A captivating subheading will go here ...</h3>
				<p>Description</p>
				<p><a class="btn btn-info" href="#" role="button">Read More</a></p>
			</div>
		</div>
		<div class="item" style="background-image:url('/images/HQ_9826.jpg');">
			<div class="carousel-caption">
				<h2>Slide 2</h2>
				<h3>A captivating subheading will go here ...</h3>
				<p>Description</p>
				<p><a class="btn btn-info" href="#" role="button">Read More</a></p>
			</div>
		</div>
	</div>

	<a class="carousel-control left" href="#myCarousel" data-slide="prev">
		<span class="icon-prev"></span>
	</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">
		<span class="icon-next"></span>
	</a>
</div>
<!-- end promo slider html -->

		
 <div class="container marketing">
	<div class="row">
	  <h1>Awesomeness for everyone!</h1>
    
    @if (Model.Content.HomeTitle != null)
    {
      <h4 style="color:aqua"> @Model.Content.HomeTitle </h4>
    }
    else
    {
      <h4 style="color:blueviolet"> no content for the homeTitle field property </h4>
    }

	    <div class="col-md-6">
	        
	        @Umbraco.Field("bodyText")

			<p><a class="btn btn-info" href="#" role="button">Read More &raquo;</a></p>
	    </div>

		<div class="col-md-6">
			<div class="col-sm-6 block-odd about-blocks" style="background-image:url('/images/HQ_0413.jpg');"></div>
			<div class="col-sm-6 block-even about-blocks" style="background-image:url('/images/HQ_9953.jpg');"></div>
			<div class="col-sm-6 block-odd about-blocks" style="background-image:url('/images/HQ_9986.jpg');"></div>
			<div class="col-sm-6 block-even about-blocks" style="background-image:url('/images/HQ_9921.jpg');"></div>
		</div>
	</div>

	<hr>

	<div class="row bottom-body">
		<h1>What can we help you find?</h1>
		<div class="col-sm-4">
			<p class="glyphicon glyphicon-globe text-center"></p>
			<h3>Knowledge</h3>
			<ul>
				<li><a href="#">The most creative ideas</a></li>
				<li><a href="#">Precise and impartial approach</a></li>
				<li><a href="#">Providing best solutions</a></li>
				<li><a href="#">Individual customer support</a></li>
				<li><a href="#">Fresh ideas for growing your business</a></li>
			</ul>
		</div>
		<div class="col-sm-4 news-items">
			<p class="glyphicon glyphicon-list-alt text-center"></p>
			<h3>Latest News</h3>
			<ul>
				<li><a href="#">Our Big News Headline 1</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 2</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 3</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 4</a><br />6/8/2015</li>
			</ul>
		</div>
		<div class="col-sm-4">
			<p class="glyphicon glyphicon-screenshot text-center"></p>
			<h3>Locations</h3>
			<ul>
				<li><a href="#">Odense, Denmark</a></li>
				<li><a href="#">Bellingham, Washington</a></li>
				<li><a href="#">Sydney, Austrailia</a></li>
				<li><a href="#">New York City, New York</a></li>
				<li><a href="#">Paris, France</a></li>
			</ul>
		</div>
	</div>
</div>

<!-- Footer Area -->
<div class="container social-area">
	<div class="row pre-footer">
		<div class="col-md-6 text-center">
			<h4>Social Media</h4>
			<div class="icons">
				<a href="#" class="facebook"></a>
				<a href="#" class="twitter"></a>
				<a href="#" class="linkedin"></a>
				<a href="#" class="github"></a>
				<a href="" class="rss"></a>
			</div>
		</div>
		<div class="col-md-6 text-center">
			<h4>Contact us</h4>
			<p>Umbraco HQ
				Haubergsvej 1<br />
				DK-5000 Odense C<br />
				+45 70 26 11 62
			</p>
		</div>
	</div>

	<div class="row base-footer">
		<div class="footer-info">
			<p class="pull-right"><a href="#">Back to top</a></p>
			<p>&#169; @(DateTime.Today.Year) Company, Inc. <a href="#">Privacy</a> | <a href="#">Terms</a></p>
		</div>
	</div>
</div>
<!-- End Footer Area -->

MvcCourse/Views/Master.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = null;
}

<!doctype html>
<html>
	<head>
		<title>@Umbraco.Field("pageName")</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="~/css/socialiconstyle.css" />
		<link rel="stylesheet" href="~/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/carousel.css" />
		<link rel="stylesheet" href="~/css/magnific-popup-lightbox.css" />
		<link rel="stylesheet" href="~/css/umasterclass.css" />

		<script type="text/javascript" src="/scripts/jquery.min.js"></script>
		<script type="text/javascript" src="/scripts/bootstrap.min.js"></script>
		<script type="text/javascript" src="/scripts/magnific-popup-lightbox.js"></script>
		<script type="text/javascript" src="/scripts/website.js"></script>
		
		<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/5.13.0/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
	    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/5.13.0/css/themes/default.min.css" type="text/css" media="screen"  charset="utf-8" />
	</head>
	<body>
		<!-- Nav -->
		<nav class="navbar navbar-inverse">
			<div class="container">
				<a href="/" class="navbar-brand">
					<img alt="Umbraco" src="/images/umbracoblack.png">
				</a>
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="collapse navbar-collapse navHeaderCollapse">
					
					<!-- Navbar -->
					@{ var selection = CurrentPage.Site().Children.Where("Visible"); }

					<ul class="nav navbar-nav">
						@foreach (var item in selection)
						{
							<li class="@(item.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
								<a href="@item.Url">@item.Name</a>
							</li>
						}
					</ul>
						
					<!-- End Navbar -->
							
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Guest<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<!-- If logged on -->
								<li><a href="/logout"><i class="glyphicon glyphicon-off"></i> Log Out</a></li>
								<!-- else -->
								<li><a href="/login"><i class="glyphicon glyphicon-lock"></i> Log In</a></li>
								<li><a href="/register"><i class="glyphicon glyphicon-pencil"></i> Register</a></li>
							</ul>
						</li>
						<li>
							<form class="navbar-form navbar-right" role="search" action="/search">
								<div class="form-group">
									<input type="text" name="q" class="form-control span2" placeholder="Search">
								</div>
							</form>
						</li>
					</ul>
				</div>
			</div> 
		</nav>
		<!-- End Nav -->
		
		<!-- Child template begins -->
		@RenderBody()
		<!-- Child template ends -->
        
        <script src="//cdn.jsdelivr.net/medium-editor/5.13.0/js/medium-editor.min.js"></script>
        <script>var editor = new MediumEditor('textarea.editable');</script>

	</body>
</html>

MvcCourse/Views/landingPage.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
	
	//get the related landing pages
    var ids = UmbracoContext
                    .Application.Services
                    .RelationService.GetByChildId(Model.Content.Id)
                    .Select(x => x.ParentId);
                    
    //fetch them as nodes
    var docs = Umbraco.TypedContent(ids)
                           .Where(x => x.DocumentTypeAlias == "documentation").ToList();
}

<div class="container">
	<div class="row">
		<div class="page-header">
				<h1>@Umbraco.Field("pageName")</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			@Umbraco.Field("productSpecSheet")
		</div>
				
		<div class="col-md-3">
			@if (docs.Any())
			{
				<ul class="nav nav-list">
					<li><h4>Documentation</h4></li>
					@foreach (var item in docs)
					{
						<li>
							<a href="@item.Url">@item.Name</a>
						</li>
					}
				</ul>
			}
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<footer>
				Updated by 
				@Umbraco.Field("writerName")
				on
				@Umbraco.Field("updateDate", formatAsDate: true)
			</footer>
		</div>
	</div>
</div>

MvcCourse/Views/textpage.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div class="page-header">
				<h1>@Umbraco.Field("pageName")</h1>
			</div>

			@Umbraco.Field("bodyText")

		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<footer>
				Updated by 
				@Umbraco.Field("writerName")
				on
				@Umbraco.Field("updateDate", formatAsDate: true)
			</footer>
		</div>
	</div>
</div>